version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"               
    volumes:
      - ./html:/usr/share/nginx/html
    depends_on:
      - db                     

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mello662     
      MYSQL_DATABASE: dockerDaniAtividade               
      MYSQL_USER: nicolasmello                         
      MYSQL_PASSWORD: mello662             
    volumes:
      - db_data:/var/lib/mysql                 

volumes:
  db_data:
